using System;
using UnityEngine;

/// <summary>
/// Represents a room that can be Generated by the Map Generator 
/// </summary>
public class GeneratedRoom : MonoBehaviour
{
    [SerializeField] BoxCollider roomBounds;
    [SerializeField] RoomConnection[] roomConnections;

    #region Initialization
    void Awake()
    {
        if (transform.localScale != Vector3.one)
        {
            Debug.LogError("The \"" + transform.name + "\" room does not have a normalized scale! It will not work correctly!");
        }
        if (roomBounds == null)
        {
            roomBounds = GetComponent<BoxCollider>();
            if (roomBounds == null)
            {
                Debug.LogError("The \"" + transform.name + "\" room does not have a room bounds setup. It will not work correctly!");
            }
        }
    }
    #endregion

    /// <summary>
    /// </summary>
    /// <param name="cellSize">The size of a cell in the map</param>
    /// <returns>The Dimensions of the room using the given cell size as reference.</returns>
    Vector2Int GetDimensions(int cellSize)
    {
        return new Vector2Int(Mathf.CeilToInt((roomBounds.size.x * roomBounds.transform.localScale.x) / cellSize), Mathf.CeilToInt((roomBounds.size.z * roomBounds.transform.localScale.z) / cellSize));
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="cellSize">The size of a cell in the map</param>
    /// <returns>The representation of this room as a Room script. Used for Map Gen</returns>
    public Room GetRoomRepresentation(int cellSize)
    {
        Vector2Int roomDimensions = GetDimensions(cellSize);

        if (roomDimensions.x % cellSize != 0) throw new InvalidOperationException($"Width of room \"{transform.root.name}\" ({roomDimensions.x}) is not valid for the given cell size ({cellSize}).");
        if (roomDimensions.y % cellSize != 0) throw new InvalidOperationException($"Height of room \"{transform.root.name}\" ({roomDimensions.y}) is not valid for the given cell size ({cellSize}).");

        return new Room(transform.root.gameObject, roomDimensions.x, roomDimensions.y);
    }

#if UNITY_EDITOR
    [Header("Editor Variables")]
    [SerializeField] int cellSizePreview;
    public int EDITOR_GetCellSizePreview() => cellSizePreview;
    public Vector2Int EDITOR_GetRowsAndColumns() => GetDimensions(cellSizePreview);
#endif
}